<form action="extensionAPI_form.asp"></form>
<input type="text" name="API_KEY" placeholder="Enter API_KEY"></input>
<form method="get" action="https://www.facebook.com/">
	<button class ="btn btn-default" type="submit">Proceed</button>
</form>
<br>
</br>
<br>
<select name="Seleccionador_API">
    <option selected="" value="0"> Select Profile </option>
	<option>Prueba</option>
</select>
</br>
<br></br>
<button id="id_Field" title="Add Field" type="button" class="scalable add" onclick="setLocation('http://localhost/magento_one/index.php/admin/catalog_product/new/key/40c6126b9b9b9ac257406a0eab5b4b20/')" style=""><span><span><span>Add Field</span></span></span></button>
<br>
<select name="Magento_List">
    <option selected="" value="0">Magento Fields List</option>
    <option>Prueba</option>
</select>
<select name="ICOMMKT_List">
    <option selected="" value="0">ICOMMKT Fields List</option>
    <option>Prueba</option>
</select>
</br>





